services:
  cookbook-dev:
    image: python:3.12-slim
    container_name: my-cookbook-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8789:8789"
    command: >
      sh -c "pip install --no-cache-dir --upgrade pip &&
      pip install --no-cache-dir -r requirements.txt &&
      mkdocs serve --dev-addr=0.0.0.0:8789"
